INFO: 2022-05-14 18:56:11,425: main() 'Using profile folder /home/donald/.config/variety/'
INFO: 2022-05-14 18:56:11,434: perform_upgrade() 'Last run version was 0.8.7 or earlier, current version is 0.8.7'
INFO: 2022-05-14 18:56:11,800: process_command() 'Received command: ['--next']'
INFO: 2022-05-14 18:56:11,804: start() 'Using data_path /usr/share/variety'
INFO: 2022-05-14 18:56:11,804: load() 'Jumble loading'
INFO: 2022-05-14 18:56:11,805: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.10/site-packages/variety/plugins/builtin/__init__.py'
INFO: 2022-05-14 18:56:11,809: _walk_modules() 'Jumble loading module in UnsplashConfigurableSource from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/UnsplashConfigurableSource.py'
INFO: 2022-05-14 18:56:11,815: load() 'Jumble found plugin class: <class 'UnsplashConfigurableSource.UnsplashConfigurableSource'>: {'name': 'UnsplashConfigurableSource', 'description': 'Configurable source for fetching photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,816: _walk_modules() 'Jumble loading module in EarthviewDownloader from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/EarthviewDownloader.py'
INFO: 2022-05-14 18:56:11,818: load() 'Jumble found plugin class: <class 'EarthviewDownloader.EarthviewDownloader'>: {'name': 'EarthviewDownloader', 'description': 'Google Earth View Wallpapers', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,821: _walk_modules() 'Jumble loading module in NationalGeographicDownloader from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/NationalGeographicDownloader.py'
INFO: 2022-05-14 18:56:11,822: load() 'Jumble found plugin class: <class 'NationalGeographicDownloader.NationalGeographicDownloader'>: {'name': 'NationalGeographicDownloader', 'description': "National Geographic's photo of the day", 'author': 'Eric RÃ¶sch', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,822: _walk_modules() 'Jumble loading module in UnsplashDownloader from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/UnsplashDownloader.py'
INFO: 2022-05-14 18:56:11,823: load() 'Jumble found plugin class: <class 'UnsplashDownloader.UnsplashDownloader'>: {'name': 'UnsplashDownloader', 'description': 'High-resolution photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,824: _walk_modules() 'Jumble loading module in ArtStationDownloader from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/ArtStationDownloader.py'
INFO: 2022-05-14 18:56:11,827: _walk_modules() 'Jumble loading module in WallhavenDownloader from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/WallhavenDownloader.py'
INFO: 2022-05-14 18:56:11,833: _walk_modules() 'Jumble loading module in WallhavenSource from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/WallhavenSource.py'
INFO: 2022-05-14 18:56:11,837: load() 'Jumble found plugin class: <class 'WallhavenSource.WallhavenSource'>: {'name': 'WallhavenSource', 'description': 'Configurable source for fetching images from Wallhaven.cc', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,838: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/__init__.py'
INFO: 2022-05-14 18:56:11,839: _walk_modules() 'Jumble loading module in RedditSource from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/RedditSource.py'
INFO: 2022-05-14 18:56:11,842: load() 'Jumble found plugin class: <class 'RedditSource.RedditSource'>: {'name': 'RedditSource', 'description': 'Configurable source for fetching images from Reddit', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,843: _walk_modules() 'Jumble loading module in ArtStationSource from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/ArtStationSource.py'
INFO: 2022-05-14 18:56:11,845: load() 'Jumble found plugin class: <class 'ArtStationSource.ArtStationSource'>: {'name': 'ArtStationSource', 'description': 'Configurable source for fetching images from ArtStation', 'author': 'Denis Gordeev', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,846: _walk_modules() 'Jumble loading module in MediaRSSSource from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/MediaRSSSource.py'
INFO: 2022-05-14 18:56:11,849: load() 'Jumble found plugin class: <class 'MediaRSSSource.MediaRSSSource'>: {'name': 'MediaRSSSource', 'description': 'Configurable source for fetching images from MediaRSS feeds', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,849: _walk_modules() 'Jumble loading module in MediaRSSDownloader from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/MediaRSSDownloader.py'
INFO: 2022-05-14 18:56:11,850: _walk_modules() 'Jumble loading module in APODDownloader from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/APODDownloader.py'
INFO: 2022-05-14 18:56:11,852: load() 'Jumble found plugin class: <class 'APODDownloader.APODDownloader'>: {'name': 'APODDownloader', 'description': 'NASA Astro Pic of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,853: _walk_modules() 'Jumble loading module in BingDownloader from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py'
INFO: 2022-05-14 18:56:11,854: load() 'Jumble found plugin class: <class 'BingDownloader.BingDownloader'>: {'name': 'BingDownloader', 'description': 'Bing Photo of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,854: _walk_modules() 'Jumble loading module in WallhavenLegacyDownloader from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/WallhavenLegacyDownloader.py'
INFO: 2022-05-14 18:56:11,855: _walk_modules() 'Jumble loading module in RedditDownloader from /usr/lib/python3.10/site-packages/variety/plugins/builtin/downloaders/RedditDownloader.py'
INFO: 2022-05-14 18:56:11,857: _walk_modules() 'Jumble loading module in UrbanDictionarySource from /usr/lib/python3.10/site-packages/variety/plugins/builtin/quotes/UrbanDictionarySource.py'
INFO: 2022-05-14 18:56:11,858: load() 'Jumble found plugin class: <class 'UrbanDictionarySource.UrbanDictionarySource'>: {'name': 'Urban Dictionary', 'description': 'Displays definitions from Urban Dictionary', 'author': 'James Miller', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,859: _walk_modules() 'Jumble loading module in QuotationsPageSource from /usr/lib/python3.10/site-packages/variety/plugins/builtin/quotes/QuotationsPageSource.py'
INFO: 2022-05-14 18:56:11,870: load() 'Jumble found plugin class: <class 'QuotationsPageSource.QuotationsPageSource'>: {'name': 'TheQuotationsPage.com', 'description': 'Fetches quotes from TheQuotationsPage.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,871: _walk_modules() 'Jumble loading module in GoodreadsSource from /usr/lib/python3.10/site-packages/variety/plugins/builtin/quotes/GoodreadsSource.py'
INFO: 2022-05-14 18:56:11,872: load() 'Jumble found plugin class: <class 'GoodreadsSource.GoodreadsSource'>: {'name': 'Goodreads', 'description': 'Fetches quotes from Goodreads.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,873: _walk_modules() 'Jumble loading module in FortuneSource from /usr/lib/python3.10/site-packages/variety/plugins/builtin/quotes/FortuneSource.py'
INFO: 2022-05-14 18:56:11,875: load() 'Jumble found plugin class: <class 'FortuneSource.FortuneSource'>: {'name': 'UNIX fortune program', 'description': 'Displays quotes using the UNIX fortune program. You may want to install additional fortune packs, e.g. fortunes-bofh-excuses.', 'author': 'Dan Jones', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,875: _walk_modules() 'Jumble loading module in LocalFilesSource from /usr/lib/python3.10/site-packages/variety/plugins/builtin/quotes/LocalFilesSource.py'
INFO: 2022-05-14 18:56:11,876: load() 'Jumble found plugin class: <class 'LocalFilesSource.LocalFilesSource'>: {'name': 'Local text files', 'description': 'Displays quotes, defined in local text files.\nPut your own txt files in: ~/.config/variety/pluginconfig/quotes/.\nThe file format is:\n\nquote -- author\n.\nsecond quote -- another author\n.\netc...\n\nExample: http://rvelthuis.de/zips/quotes.txt', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2022-05-14 18:56:11,877: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.10/site-packages/variety/plugins/builtin/quotes/__init__.py'
INFO: 2022-05-14 18:56:11,906: log_options() 'Loaded options:'
INFO: 2022-05-14 18:56:11,906: log_options() 'change_enabled = True'
INFO: 2022-05-14 18:56:11,906: log_options() 'change_interval = 120'
INFO: 2022-05-14 18:56:11,906: log_options() 'change_on_start = True'
INFO: 2022-05-14 18:56:11,906: log_options() 'clipboard_enabled = False'
INFO: 2022-05-14 18:56:11,907: log_options() 'clipboard_hosts = ['wallhaven.cc', 'wallpapers.net', 'flickr.com', 'imgur.com', 'deviantart.com', 'interfacelift.com', 'vladstudio.com', 'imageshack.us', 'deviantart.net', 'imageshack.com']'
INFO: 2022-05-14 18:56:11,907: log_options() 'clipboard_use_whitelist = True'
INFO: 2022-05-14 18:56:11,907: log_options() 'clock_date_font = Serif 30'
INFO: 2022-05-14 18:56:11,907: log_options() 'clock_enabled = False'
INFO: 2022-05-14 18:56:11,907: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2022-05-14 18:56:11,907: log_options() 'clock_font = Serif 70'
INFO: 2022-05-14 18:56:11,907: log_options() 'configfile = /home/donald/.config/variety/variety.conf'
INFO: 2022-05-14 18:56:11,907: log_options() 'copyto_enabled = False'
INFO: 2022-05-14 18:56:11,907: log_options() 'copyto_folder = Default'
INFO: 2022-05-14 18:56:11,907: log_options() 'desired_color = [160, 160, 160]'
INFO: 2022-05-14 18:56:11,907: log_options() 'desired_color_enabled = False'
INFO: 2022-05-14 18:56:11,907: log_options() 'download_folder = /home/donald/.config/variety/Downloaded'
INFO: 2022-05-14 18:56:11,908: log_options() 'download_preference_ratio = 0.9'
INFO: 2022-05-14 18:56:11,908: log_options() 'favorites_folder = /home/donald/.config/variety/Favorites'
INFO: 2022-05-14 18:56:11,908: log_options() 'favorites_operations = [['Downloaded', 'Copy'], ['Fetched', 'Move'], ['Others', 'Copy']]'
INFO: 2022-05-14 18:56:11,908: log_options() 'fetched_folder = /home/donald/.config/variety/Fetched'
INFO: 2022-05-14 18:56:11,908: log_options() 'filters = [[False, 'Keep original', ''], [False, 'Grayscale', '-type Grayscale'], [False, 'Heavy blur', '-blur 120x40'], [False, 'Soft blur', '-blur 20x7'], [False, 'Oil painting', '-paint 8'], [False, 'Pointilism', '-spread 10 -noise 3'], [False, 'Pixellate', '-scale 3% -scale 3333%']]'
INFO: 2022-05-14 18:56:11,908: log_options() 'get_wallpaper_script = /home/donald/.config/variety/scripts/get_wallpaper'
INFO: 2022-05-14 18:56:11,908: log_options() 'icon = Light'
INFO: 2022-05-14 18:56:11,908: log_options() 'internet_enabled = False'
INFO: 2022-05-14 18:56:11,908: log_options() 'lightness_enabled = False'
INFO: 2022-05-14 18:56:11,908: log_options() 'lightness_mode = 0'
INFO: 2022-05-14 18:56:11,908: log_options() 'min_rating = 4'
INFO: 2022-05-14 18:56:11,908: log_options() 'min_rating_enabled = False'
INFO: 2022-05-14 18:56:11,908: log_options() 'min_size = 80'
INFO: 2022-05-14 18:56:11,908: log_options() 'min_size_enabled = False'
INFO: 2022-05-14 18:56:11,908: log_options() 'quota_enabled = True'
INFO: 2022-05-14 18:56:11,909: log_options() 'quota_size = 1000'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_authors = '
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_bg_opacity = 55'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_change_enabled = False'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_change_interval = 300'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_disabled_sources = ['Urban Dictionary']'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_enabled = False'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_favorites_file = /home/donald/.config/variety/favorite_quotes.txt'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_font = Serif 30'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_hpos = 100'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_max_length = 250'
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_tags = '
INFO: 2022-05-14 18:56:11,909: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2022-05-14 18:56:11,910: log_options() 'quotes_text_shadow = False'
INFO: 2022-05-14 18:56:11,910: log_options() 'quotes_vpos = 40'
INFO: 2022-05-14 18:56:11,910: log_options() 'quotes_width = 70'
INFO: 2022-05-14 18:56:11,910: log_options() 'safe_mode = False'
INFO: 2022-05-14 18:56:11,910: log_options() 'set_wallpaper_script = /home/donald/.config/variety/scripts/set_wallpaper'
INFO: 2022-05-14 18:56:11,910: log_options() 'slideshow_custom_enabled = False'
INFO: 2022-05-14 18:56:11,910: log_options() 'slideshow_custom_folder = /home/donald/Pictures'
INFO: 2022-05-14 18:56:11,910: log_options() 'slideshow_downloads_enabled = False'
INFO: 2022-05-14 18:56:11,910: log_options() 'slideshow_fade = 0.4'
INFO: 2022-05-14 18:56:11,910: log_options() 'slideshow_favorites_enabled = True'
INFO: 2022-05-14 18:56:11,910: log_options() 'slideshow_mode = Fullscreen'
INFO: 2022-05-14 18:56:11,910: log_options() 'slideshow_monitor = All'
INFO: 2022-05-14 18:56:11,910: log_options() 'slideshow_pan = 0.05'
INFO: 2022-05-14 18:56:11,910: log_options() 'slideshow_seconds = 6.0'
INFO: 2022-05-14 18:56:11,910: log_options() 'slideshow_sort_order = Random'
INFO: 2022-05-14 18:56:11,911: log_options() 'slideshow_sources_enabled = True'
INFO: 2022-05-14 18:56:11,911: log_options() 'slideshow_zoom = 0.2'
INFO: 2022-05-14 18:56:11,911: log_options() 'smart_enabled = False'
INFO: 2022-05-14 18:56:11,911: log_options() 'smart_notice_shown = False'
INFO: 2022-05-14 18:56:11,911: log_options() 'smart_register_shown = False'
INFO: 2022-05-14 18:56:11,911: log_options() 'sources = [[True, 'favorites', 'The Favorites folder'], [False, 'fetched', 'The Fetched folder'], [False, 'folder', '/usr/share/backgrounds'], [False, 'flickr', 'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'], [False, 'apod', "NASA's Astronomy Picture of the Day"], [False, 'bing', 'Bing Photo of the Day'], [False, 'earthview', 'Google Earth View Wallpapers'], [False, 'natgeo', "National Geographic's photo of the day"], [False, 'unsplash', 'High-resolution photos from Unsplash.com']]'
INFO: 2022-05-14 18:56:11,911: log_options() 'stats_enabled = True'
INFO: 2022-05-14 18:56:11,911: log_options() 'stats_notice_shown = False'
INFO: 2022-05-14 18:56:11,911: log_options() 'sync_enabled = True'
INFO: 2022-05-14 18:56:11,911: log_options() 'use_landscape_enabled = True'
INFO: 2022-05-14 18:56:11,911: log_options() 'wallhaven_api_key = '
INFO: 2022-05-14 18:56:11,911: reload_config() 'No need to clear prepared queue'
INFO: 2022-05-14 18:56:11,911: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png'
INFO: 2022-05-14 18:56:11,930: load_banned() 'Missing or invalid banned URLs list, no URLs will be banned'
INFO: 2022-05-14 18:56:11,930: load_last_change_time() 'Change interval < 6 hours, ignore persisted last_change_time, wait initially the whole interval: 120'
INFO: 2022-05-14 18:56:11,930: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png'
INFO: 2022-05-14 18:56:11,933: regular_change_thread() 'regular_change thread running'
INFO: 2022-05-14 18:56:11,934: prepare_thread() 'Prepare thread running'
INFO: 2022-05-14 18:56:11,934: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2022-05-14 18:56:11,934: prepare_thread() 'Preparing some images'
INFO: 2022-05-14 18:56:11,938: update_indicator_icon() 'Creating indicator'
WARNING: 2022-05-14 18:56:11,954: create_menu() 'Variety Slideshow is not installed. This is an optional extension adding pan-and-zoom slideshows to Variety: see https://github.com/peterlevi/variety-slideshow for details'
INFO: 2022-05-14 18:56:11,956: create_indicator() 'indicator backend: AppIndicator3'
INFO: 2022-05-14 18:56:11,988: set_from_theme_icon() 'Showing indicator icon variety-indicator from GTK theme'
INFO: 2022-05-14 18:56:12,009: prepare_thread() 'After search prepared buffer contains 34 images'
INFO: 2022-05-14 18:56:12,034: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png, time: 1652572572.034196'
INFO: 2022-05-14 18:56:12,052: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png'
ERROR: 2022-05-14 18:56:12,980: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png', 'refresh', '/home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png']' returned non-zero exit status 2.
INFO: 2022-05-14 18:56:13,825: reload() 'Reloading preferences dialog'
INFO: 2022-05-14 18:56:14,009: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 18:56:14,805: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/endeavour_flavours.png'
INFO: 2022-05-14 18:56:14,806: prepare_thread() 'Prepared buffer contains 33 images'
INFO: 2022-05-14 18:56:14,806: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/endeavour_flavours.png, time: 1652572574.8066056'
INFO: 2022-05-14 18:56:14,824: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/endeavour_flavours.png'
ERROR: 2022-05-14 18:56:15,548: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/endeavour_flavours.png', 'auto', '/home/donald/.config/variety/Favorites/endeavour_flavours.png']' returned non-zero exit status 2.
INFO: 2022-05-14 18:56:16,807: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 18:56:16,933: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/Endy_vector_EOS-planet.png'
INFO: 2022-05-14 18:56:16,934: prepare_thread() 'Prepared buffer contains 32 images'
INFO: 2022-05-14 18:56:16,934: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/Endy_vector_EOS-planet.png, time: 1652572576.9346344'
INFO: 2022-05-14 18:56:16,946: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/Endy_vector_EOS-planet.png'
ERROR: 2022-05-14 18:56:17,465: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/Endy_vector_EOS-planet.png', 'auto', '/home/donald/.config/variety/Favorites/Endy_vector_EOS-planet.png']' returned non-zero exit status 2.
INFO: 2022-05-14 18:56:18,934: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 18:58:17,466: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 18:58:17,466: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/EOS_3_4K.png'
INFO: 2022-05-14 18:58:17,467: prepare_thread() 'Prepared buffer contains 31 images'
INFO: 2022-05-14 18:58:17,467: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/EOS_3_4K.png, time: 1652572697.4679687'
INFO: 2022-05-14 18:58:17,483: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/EOS_3_4K.png'
ERROR: 2022-05-14 18:58:18,000: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/EOS_3_4K.png', 'auto', '/home/donald/.config/variety/Favorites/EOS_3_4K.png']' returned non-zero exit status 2.
INFO: 2022-05-14 18:58:19,468: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:00:18,001: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:00:18,001: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/APOLLO-MOON.png'
INFO: 2022-05-14 19:00:18,001: prepare_thread() 'Prepared buffer contains 30 images'
INFO: 2022-05-14 19:00:18,002: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/APOLLO-MOON.png, time: 1652572818.0025725'
INFO: 2022-05-14 19:00:18,016: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/APOLLO-MOON.png'
ERROR: 2022-05-14 19:00:18,533: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/APOLLO-MOON.png', 'auto', '/home/donald/.config/variety/Favorites/APOLLO-MOON.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:00:20,002: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:02:18,533: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:02:18,533: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/Endy_conquest_1140P_16-9_centered.png'
INFO: 2022-05-14 19:02:18,534: prepare_thread() 'Prepared buffer contains 29 images'
INFO: 2022-05-14 19:02:18,534: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/Endy_conquest_1140P_16-9_centered.png, time: 1652572938.5344298'
INFO: 2022-05-14 19:02:18,546: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/Endy_conquest_1140P_16-9_centered.png'
ERROR: 2022-05-14 19:02:18,914: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/Endy_conquest_1140P_16-9_centered.png', 'auto', '/home/donald/.config/variety/Favorites/Endy_conquest_1140P_16-9_centered.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:02:20,534: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:04:18,915: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:04:18,916: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/APOLLO-ROCKET-FLAT.png'
INFO: 2022-05-14 19:04:18,916: prepare_thread() 'Prepared buffer contains 28 images'
INFO: 2022-05-14 19:04:18,917: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/APOLLO-ROCKET-FLAT.png, time: 1652573058.9172552'
INFO: 2022-05-14 19:04:18,931: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/APOLLO-ROCKET-FLAT.png'
ERROR: 2022-05-14 19:04:19,447: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/APOLLO-ROCKET-FLAT.png', 'auto', '/home/donald/.config/variety/Favorites/APOLLO-ROCKET-FLAT.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:04:20,917: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:06:19,448: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:06:19,448: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/EOS_MISSION_BADGE_4K.png'
INFO: 2022-05-14 19:06:19,449: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/EOS_MISSION_BADGE_4K.png, time: 1652573179.4490852'
INFO: 2022-05-14 19:06:19,449: prepare_thread() 'Prepared buffer contains 27 images'
INFO: 2022-05-14 19:06:19,459: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/EOS_MISSION_BADGE_4K.png'
ERROR: 2022-05-14 19:06:20,026: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/EOS_MISSION_BADGE_4K.png', 'auto', '/home/donald/.config/variety/Favorites/EOS_MISSION_BADGE_4K.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:06:21,449: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:08:20,026: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:08:20,027: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/EOS_SPACEMAN_4K.png'
INFO: 2022-05-14 19:08:20,027: prepare_thread() 'Prepared buffer contains 26 images'
INFO: 2022-05-14 19:08:20,028: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/EOS_SPACEMAN_4K.png, time: 1652573300.0282397'
INFO: 2022-05-14 19:08:20,040: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/EOS_SPACEMAN_4K.png'
ERROR: 2022-05-14 19:08:20,660: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/EOS_SPACEMAN_4K.png', 'auto', '/home/donald/.config/variety/Favorites/EOS_SPACEMAN_4K.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:08:22,029: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:10:20,661: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:10:20,661: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/LAUNCH-Morning.png'
INFO: 2022-05-14 19:10:20,661: prepare_thread() 'Prepared buffer contains 25 images'
INFO: 2022-05-14 19:10:20,662: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/LAUNCH-Morning.png, time: 1652573420.6625915'
INFO: 2022-05-14 19:10:20,675: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/LAUNCH-Morning.png'
ERROR: 2022-05-14 19:10:21,191: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/LAUNCH-Morning.png', 'auto', '/home/donald/.config/variety/Favorites/LAUNCH-Morning.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:10:22,663: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:12:21,192: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:12:21,192: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/northernlass_endeavour_gallion.png'
INFO: 2022-05-14 19:12:21,192: prepare_thread() 'Prepared buffer contains 24 images'
INFO: 2022-05-14 19:12:21,193: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/northernlass_endeavour_gallion.png, time: 1652573541.1935205'
INFO: 2022-05-14 19:12:21,209: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/northernlass_endeavour_gallion.png'
ERROR: 2022-05-14 19:12:21,475: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/northernlass_endeavour_gallion.png', 'auto', '/home/donald/.config/variety/Favorites/northernlass_endeavour_gallion.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:12:23,193: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:14:21,476: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:14:21,476: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/neon_astronaut_endeavor.jpg'
INFO: 2022-05-14 19:14:21,477: prepare_thread() 'Prepared buffer contains 23 images'
INFO: 2022-05-14 19:14:21,477: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/neon_astronaut_endeavor.jpg, time: 1652573661.4779162'
INFO: 2022-05-14 19:14:21,489: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/neon_astronaut_endeavor.jpg'
ERROR: 2022-05-14 19:14:21,755: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/neon_astronaut_endeavor.jpg', 'auto', '/home/donald/.config/variety/Favorites/neon_astronaut_endeavor.jpg']' returned non-zero exit status 2.
INFO: 2022-05-14 19:14:23,478: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:16:21,756: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:16:21,756: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/blinky_4.jpg'
INFO: 2022-05-14 19:16:21,757: prepare_thread() 'Prepared buffer contains 22 images'
INFO: 2022-05-14 19:16:21,757: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/blinky_4.jpg, time: 1652573781.7576556'
INFO: 2022-05-14 19:16:21,769: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/blinky_4.jpg'
ERROR: 2022-05-14 19:16:22,086: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/blinky_4.jpg', 'auto', '/home/donald/.config/variety/Favorites/blinky_4.jpg']' returned non-zero exit status 2.
INFO: 2022-05-14 19:16:23,758: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:18:22,087: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:18:22,087: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/eos_xfcei3_2.png'
INFO: 2022-05-14 19:18:22,087: prepare_thread() 'Prepared buffer contains 21 images'
INFO: 2022-05-14 19:18:22,087: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/eos_xfcei3_2.png, time: 1652573902.087897'
INFO: 2022-05-14 19:18:22,099: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/eos_xfcei3_2.png'
ERROR: 2022-05-14 19:18:22,642: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/eos_xfcei3_2.png', 'auto', '/home/donald/.config/variety/Favorites/eos_xfcei3_2.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:18:24,088: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:20:22,643: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:20:22,643: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/blinky_6.jpg'
INFO: 2022-05-14 19:20:22,643: prepare_thread() 'Prepared buffer contains 20 images'
INFO: 2022-05-14 19:20:22,644: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/blinky_6.jpg, time: 1652574022.644037'
INFO: 2022-05-14 19:20:22,658: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/blinky_6.jpg'
ERROR: 2022-05-14 19:20:23,227: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/blinky_6.jpg', 'auto', '/home/donald/.config/variety/Favorites/blinky_6.jpg']' returned non-zero exit status 2.
INFO: 2022-05-14 19:20:24,644: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:22:23,228: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:22:23,228: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/krimkerre_2_poly.jpg'
INFO: 2022-05-14 19:22:23,229: prepare_thread() 'Prepared buffer contains 19 images'
INFO: 2022-05-14 19:22:23,229: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/krimkerre_2_poly.jpg, time: 1652574143.2298038'
INFO: 2022-05-14 19:22:23,244: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/krimkerre_2_poly.jpg'
ERROR: 2022-05-14 19:22:23,509: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/krimkerre_2_poly.jpg', 'auto', '/home/donald/.config/variety/Favorites/krimkerre_2_poly.jpg']' returned non-zero exit status 2.
INFO: 2022-05-14 19:22:25,229: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:24:23,510: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:24:23,510: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png'
INFO: 2022-05-14 19:24:23,510: prepare_thread() 'Prepared buffer contains 18 images'
INFO: 2022-05-14 19:24:23,511: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png, time: 1652574263.5110133'
INFO: 2022-05-14 19:24:23,525: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png'
ERROR: 2022-05-14 19:24:24,044: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png', 'auto', '/home/donald/.config/variety/Favorites/Endeavouros_shuttle_backdrop.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:24:25,511: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:26:24,044: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:26:24,045: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/LAUNCH.png'
INFO: 2022-05-14 19:26:24,045: prepare_thread() 'Prepared buffer contains 17 images'
INFO: 2022-05-14 19:26:24,046: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/LAUNCH.png, time: 1652574384.04645'
INFO: 2022-05-14 19:26:24,060: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/LAUNCH.png'
ERROR: 2022-05-14 19:26:24,527: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/LAUNCH.png', 'auto', '/home/donald/.config/variety/Favorites/LAUNCH.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:26:26,046: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:28:24,528: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:28:24,528: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/Endeavouros_shuttle.png'
INFO: 2022-05-14 19:28:24,529: prepare_thread() 'Prepared buffer contains 16 images'
INFO: 2022-05-14 19:28:24,530: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/Endeavouros_shuttle.png, time: 1652574504.5300496'
INFO: 2022-05-14 19:28:24,542: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/Endeavouros_shuttle.png'
ERROR: 2022-05-14 19:28:24,859: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/Endeavouros_shuttle.png', 'auto', '/home/donald/.config/variety/Favorites/Endeavouros_shuttle.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:28:26,530: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:30:24,860: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:30:24,860: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/EOS_2_4K.jpg'
INFO: 2022-05-14 19:30:24,860: prepare_thread() 'Prepared buffer contains 15 images'
INFO: 2022-05-14 19:30:24,861: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/EOS_2_4K.jpg, time: 1652574624.8618596'
INFO: 2022-05-14 19:30:24,874: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/EOS_2_4K.jpg'
ERROR: 2022-05-14 19:30:25,140: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/EOS_2_4K.jpg', 'auto', '/home/donald/.config/variety/Favorites/EOS_2_4K.jpg']' returned non-zero exit status 2.
INFO: 2022-05-14 19:30:26,861: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:32:25,141: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:32:25,141: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/eos-man-4k.png'
INFO: 2022-05-14 19:32:25,141: prepare_thread() 'Prepared buffer contains 14 images'
INFO: 2022-05-14 19:32:25,141: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/eos-man-4k.png, time: 1652574745.1418052'
INFO: 2022-05-14 19:32:25,154: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/eos-man-4k.png'
ERROR: 2022-05-14 19:32:25,720: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/eos-man-4k.png', 'auto', '/home/donald/.config/variety/Favorites/eos-man-4k.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:32:27,142: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:34:25,721: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:34:25,722: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/Endy_vector_EOS-planet_ultrawide.png'
INFO: 2022-05-14 19:34:25,722: prepare_thread() 'Prepared buffer contains 13 images'
INFO: 2022-05-14 19:34:25,723: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/Endy_vector_EOS-planet_ultrawide.png, time: 1652574865.7235572'
INFO: 2022-05-14 19:34:25,737: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/Endy_vector_EOS-planet_ultrawide.png'
ERROR: 2022-05-14 19:34:26,103: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/Endy_vector_EOS-planet_ultrawide.png', 'auto', '/home/donald/.config/variety/Favorites/Endy_vector_EOS-planet_ultrawide.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:34:27,723: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:36:26,104: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:36:26,104: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/flval_eos_amour.jpeg'
INFO: 2022-05-14 19:36:26,105: prepare_thread() 'Prepared buffer contains 12 images'
INFO: 2022-05-14 19:36:26,106: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/flval_eos_amour.jpeg, time: 1652574986.1065626'
INFO: 2022-05-14 19:36:26,120: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/flval_eos_amour.jpeg'
ERROR: 2022-05-14 19:36:26,385: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/flval_eos_amour.jpeg', 'auto', '/home/donald/.config/variety/Favorites/flval_eos_amour.jpeg']' returned non-zero exit status 2.
INFO: 2022-05-14 19:36:28,106: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:38:26,386: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:38:26,387: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/krimkerre_4_endy_neon.jpg'
INFO: 2022-05-14 19:38:26,387: prepare_thread() 'Prepared buffer contains 11 images'
INFO: 2022-05-14 19:38:26,388: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/krimkerre_4_endy_neon.jpg, time: 1652575106.388705'
INFO: 2022-05-14 19:38:26,400: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/krimkerre_4_endy_neon.jpg'
ERROR: 2022-05-14 19:38:26,666: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/krimkerre_4_endy_neon.jpg', 'auto', '/home/donald/.config/variety/Favorites/krimkerre_4_endy_neon.jpg']' returned non-zero exit status 2.
INFO: 2022-05-14 19:38:28,388: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:40:26,666: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:40:26,667: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/LAUNCH-SUNRISE.png'
INFO: 2022-05-14 19:40:26,667: prepare_thread() 'Prepared buffer contains 10 images'
INFO: 2022-05-14 19:40:26,668: prepare_thread() 'Preparing some images'
INFO: 2022-05-14 19:40:26,668: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/LAUNCH-SUNRISE.png, time: 1652575226.6686661'
INFO: 2022-05-14 19:40:26,677: prepare_thread() 'After search prepared buffer contains 34 images'
INFO: 2022-05-14 19:40:26,685: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/LAUNCH-SUNRISE.png'
ERROR: 2022-05-14 19:40:27,151: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/LAUNCH-SUNRISE.png', 'auto', '/home/donald/.config/variety/Favorites/LAUNCH-SUNRISE.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:40:28,677: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:42:27,152: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:42:27,153: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/LAUNCH-Morning.png'
INFO: 2022-05-14 19:42:27,153: prepare_thread() 'Prepared buffer contains 33 images'
INFO: 2022-05-14 19:42:27,154: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/LAUNCH-Morning.png, time: 1652575347.1541798'
INFO: 2022-05-14 19:42:27,169: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/LAUNCH-Morning.png'
ERROR: 2022-05-14 19:42:27,635: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/LAUNCH-Morning.png', 'auto', '/home/donald/.config/variety/Favorites/LAUNCH-Morning.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:42:29,154: trigger_download() 'Triggering download thread to check if download needed and possible'
INFO: 2022-05-14 19:44:27,636: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2022-05-14 19:44:27,637: set_wallpaper() 'Calling set_wallpaper with /home/donald/.config/variety/Favorites/APOLLO-ROCKET-FLAT.png'
INFO: 2022-05-14 19:44:27,637: prepare_thread() 'Prepared buffer contains 32 images'
INFO: 2022-05-14 19:44:27,638: do_set_wp() 'Calling do_set_wp with /home/donald/.config/variety/Favorites/APOLLO-ROCKET-FLAT.png, time: 1652575467.6382792'
INFO: 2022-05-14 19:44:27,653: update_indicator() 'Setting file info to: /home/donald/.config/variety/Favorites/APOLLO-ROCKET-FLAT.png'
ERROR: 2022-05-14 19:44:28,069: set_desktop_wallpaper() 'Exception when calling set_wallpaper script: 2'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/variety/VarietyWindow.py", line 2676, in set_desktop_wallpaper
    subprocess.check_call([script, wallpaper, auto, original_file], timeout=10)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/donald/.config/variety/scripts/set_wallpaper', '/home/donald/.config/variety/Favorites/APOLLO-ROCKET-FLAT.png', 'auto', '/home/donald/.config/variety/Favorites/APOLLO-ROCKET-FLAT.png']' returned non-zero exit status 2.
INFO: 2022-05-14 19:44:29,638: trigger_download() 'Triggering download thread to check if download needed and possible'
